package com.alderangaming.wizardsencounters;

public class DefinitionTutorial
{

	public static final String[] TUTORIAL_TEXT =
		{ "Welcome to Wizards: Encounters, the 3rd installment of the Wizards RPG series! Wizards: Encounters is a loot/round based roguelike RPG, built around obtaining new class and ability runes, as well as getting as far as you can in the rounds. When you first start out, you'll be able to create a character with as the only class rune you have. After created, tap on your character, and you'll either be able to browse your Inventory, or Start Round 1. In the inventory, you can view the items you currently have, as well as the ability and class runes you can assign to your current class. You can also browse the Store, which you can purchase items to be used on your character. You're able to start a new round by selecting your character, and tapping on Start Round. Remember, once you start a round, you'll need to finish it, so make sure you have enough time to finish the rounds. Failure to finish a round will DELETE YOUR CHARACTER.  Also, if you die in a round, your character will be DELETED. A round consists of 5 monsters, each with a central theme.  Survive all 5 monsters, and you'll be rewarded with treasure chests, with loot!  Also, after defeating each monster, you will be given GOLD that you can spend at the store, or to open treasure chests. Round 5 has a BOSS monster.  Defeating the BOSS on Round 5 will give you much better loot, as well as ranking up your character (to rank 2.)  If you decide to CHECK OUT at this point, you will start back at ROUND 1. Defeating BOSS monsters will drop CLASS and ABILITY runes, so you'll be able to create new characters with new classes, as well as equipping your current characters with new ABILITIES that have dropped. There are 6 types of items that could drop, or you could purchase from the STORE.  Weapons, Helm, Chest, Shoes, Trinket, Item, Class Runes and Ability Runes.  Class and Ability runes mostly drop from BOSS monsters. Two ITEMS can be equipped on your character at one time.  Once you buy an ITEM (Such as HEALTH POTION,) it gives you 1 of 1 charges in that ITEM.  Some ITEMS, such as HEALTH POTION, allow you to buy more charges for that item.  Some items replenish these charges at the end of each round, some do not.  If you need to replenish an item's charges, you can do so in the INVENTORY screen.  Some ITEMS will max out in the amount of charges they can carry, some can only carry 1 charge. Each of your characters share the same loot.  There is no individual INVENTORY for each character.  If your first character uses the CLOUD 1/1 item, that will make it CLOUD 0/1.  If another character attempts to use the CLOUD 0/1, they will be unable until they go to the INVENTORY and purchase another CHARGE." };

}
